# Generated by Django 5.2.4 on 2025-10-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(default='Project Name', max_length=100)),
                ('Project_manager', models.CharField(default='Project Manager', max_length=100)),
                ('Project_desc', models.CharField(default='Project Description', max_length=300)),
            ],
        ),
    ]
