# Generated by Django 5.2.4 on 2025-10-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpcommingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_name', models.CharField(default='Event Name', max_length=100)),
                ('Event_desc', models.CharField(default='Event Description', max_length=200)),
                ('Event_img', models.ImageField(blank=True, null=True, upload_to='UpcommingEvents/images')),
                ('Event_title', models.CharField(default='Event Title', max_length=100)),
            ],
        ),
    ]
