# Generated by Django 5.2.4 on 2025-10-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpcommintEvents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcommingevents',
            name='Event_desc',
            field=models.CharField(default='Event Description'),
        ),
    ]
