# Generated by Django 5.2.4 on 2025-10-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(default='Category Name', max_length=100)),
                ('Category_desc', models.TextField(default='No description')),
                ('Category_img', models.ImageField(blank=True, null=True, upload_to='category/images')),
            ],
        ),
    ]
