# Generated by Django 5.2.4 on 2025-10-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Name', max_length=100)),
                ('Score', models.IntegerField(default=0)),
                ('Rank', models.IntegerField(default=0)),
                ('Profile_img', models.ImageField(blank=True, null=True, upload_to='Leaderboard/images')),
            ],
        ),
    ]
