# Generated by Django 5.2.4 on 2025-10-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='Features_desc',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='features',
            name='Features_img',
            field=models.ImageField(blank=True, null=True, upload_to='service/images'),
        ),
        migrations.AddField(
            model_name='features',
            name='Features_name',
            field=models.CharField(default='Feature Name', max_length=100),
        ),
        migrations.AddField(
            model_name='features',
            name='Features_price',
            field=models.CharField(default='Free', max_length=100),
        ),
    ]
